apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: notes-app
type: Opaque
stringData:
  POSTGRES_DB: notesdb
  POSTGRES_USER: notes_user
  POSTGRES_PASSWORD: notes_pass
  DATABASE_URL: postgresql://notes_user:notes_pass@postgres:5432/notesdb
